version: "3.3"
services:
  digiforest_docker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: digiforest_docker
    tty: true
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ../media:/digiforest_ws/media
